export const LOCATION_STRINGS = {
  statusCalculable: 'Calculable',
  statusIncomplete: 'Datos pendientes',
  labelLocation: 'Ubicacion',
  labelAddress: 'Direccion',
  labelZipCode: 'Codigo postal',
  labelState: 'Estado',
  labelMunicipality: 'Municipio',
  labelNeighborhood: 'Colonia',
  labelCity: 'Ciudad',
  labelCatZone: 'Zona catastrofica',
  labelConstructionType: 'Tipo constructivo',
  labelLevel: 'Nivel',
  labelConstructionYear: 'Ano de construccion',
  labelBusinessLine: 'Giro comercial',
  labelGuarantees: 'Coberturas',
  labelIndex: '#',
  labelValidationStatus: 'Estado',
  labelActions: 'Acciones',
  errorFolioNotFound: 'El folio no existe',
  errorGeneric: 'Ocurrio un error. Intenta de nuevo.',
  errorVersionConflict:
    'El folio fue modificado por otro proceso. Recargue para continuar.',
};
