export const SAVE_LOCATIONS_STRINGS = {
  titleNew: 'Nueva ubicación',
  titleEdit: 'Editar ubicación',
  step1Label: 'Datos del inmueble',
  step2Label: 'Coberturas',
  btnNext: 'Siguiente → Coberturas',
  btnBack: '← Atrás',
  btnSave: 'Guardar ubicación',
  btnCancel: 'Cancelar',
  labelLocationName: 'Nombre de la ubicación',
  labelAddress: 'Dirección',
  labelZipCode: 'Código postal',
  labelAutoResolved: 'Datos resueltos automáticamente',
  labelConstructionType: 'Tipo constructivo',
  labelLevel: 'Nivel',
  labelConstructionYear: 'Año de construcción',
  labelBusinessLine: 'Giro comercial',
  placeholderBusinessLine: 'Buscar giro...',
  helperBusinessLine: 'El giro determina las tasas de riesgo aplicables',
  labelCoverages: 'Coberturas activas',
  textCoveragesHelper: 'Selecciona las coberturas y define la suma asegurada para cada una',
  labelInsuredAmount: 'Suma asegurada',
  badgeRecommended: 'Recomendado',
  cpResolving: 'Resolviendo...',
  cpResolved: 'Resuelto ✓',
  cpNotFound: 'Código postal no encontrado. Puedes continuar con la captura, pero la ubicación quedará pendiente.',
  cpServiceUnavailable: 'El servicio de catálogos no está disponible. Intenta en unos momentos.',
  btnRetry: 'Reintentar',
};
